# -*- coding: utf-8 -*-
"""EXP05-BIGDATA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ub8qBLOaykp240J3oQoMeJTFDo5bbUwb

# ANALYSIS AND VISUALIZATION OF COVID-19 DATASET

# 1. Load and Explore the Dataset
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/covid_case (1).csv")

# Display first few rows
print("----- First 5 Records -----")
print(df.head())

# Display dataset shape
print("\nDataset Shape (Rows, Columns):", df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Check for missing values
print("\nMissing Values in Each Column:")
print(df.isnull().sum())

# Handle missing data (if any) by filling with 0 or dropping
df.fillna(0, inplace=True)

"""# 2. Basic Data Exploration"""

# Total number of records
print("\nTotal Number of Records:", len(df))

# Statistical summary
print("\n----- Statistical Summary -----")
print(df.describe())

"""# 3. Visualization using Matplotlib"""

# To make plots look better
plt.style.use('seaborn-v0_8')
plt.rcParams['figure.figsize'] = (10, 6)

"""## Line Graph: Trend of confirmed cases over time (Globally)"""

df['Date'] = pd.to_datetime(df['Date'])
global_trend = df.groupby('Date')['Confirmed'].sum()

plt.figure()
plt.plot(global_trend.index, global_trend.values, color='blue', marker='o')
plt.title("Global Trend of Confirmed COVID-19 Cases Over Time")
plt.xlabel("Date")
plt.ylabel("Number of Confirmed Cases")
plt.grid(True)
plt.show()

"""## Bar Chart: Top 10 countries by total confirmed cases"""

country_confirmed = df.groupby('Country')['Confirmed'].sum().sort_values(ascending=False).head(10)

plt.figure()
country_confirmed.plot(kind='bar', color='orange')
plt.title("Top 10 Countries by Total Confirmed Cases")
plt.xlabel("Country")
plt.ylabel("Total Confirmed Cases")
plt.xticks(rotation=45)
plt.show()

"""## Pie Chart: Case distribution of top 5 affected countries"""

top5 = df.groupby('Country')['Confirmed'].sum().sort_values(ascending=False).head(5)

plt.figure()
plt.pie(top5, labels=top5.index, autopct='%1.1f%%', startangle=140)
plt.title("Case Distribution of Top 5 Affected Countries")
plt.show()

"""## Scatter Plot: Relation between Confirmed and Deaths"""

plt.figure()
plt.scatter(df['Confirmed'], df['Deaths'], color='red', alpha=0.5)
plt.title("Relationship between Confirmed Cases and Deaths")
plt.xlabel("Confirmed Cases")
plt.ylabel("Deaths")
plt.grid(True)
plt.show()

"""## Histogram: Distribution of Active Cases"""

plt.figure()
plt.hist(df['Active'], bins=20, color='green', edgecolor='black')
plt.title("Distribution of Active COVID-19 Cases")
plt.xlabel("Active Cases")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()